date=15;
part1="Täna";
part2="on";
part3="neljapäev";
month="oktoober";
year=2015;
string=part1+" "+part2+" "+part3+", "+date+"."+" "+month+" "+year;
console.log(string);
a=15;
b=5;
vahe=a-b;
console.log(a+"-"+b+"="+vahe);