-- MySQL Script generated by MySQL Workbench
-- 02/14/15 10:37:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema haide
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema haide
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `haide` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `haide` ;

-- -----------------------------------------------------
-- Table `haide`.`Autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haide`.`Autor` (
  `idAUtor` INT NOT NULL,
  `Eesnimi` VARCHAR(45) NOT NULL,
  `Perekonnanimi` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAUtor`),
  INDEX `autor_perekonnanimi` (`Perekonnanimi` ASC),
  UNIQUE INDEX `autor_nimi_perekonnanimi` (`Eesnimi` ASC, `Perekonnanimi` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haide`.`Teos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haide`.`Teos` (
  `idPealkiri` INT NOT NULL,
  `Pealkiri` VARCHAR(45) NOT NULL,
  `lk_arv` INT NOT NULL,
  `ilmumisaeg` YEAR NULL,
  PRIMARY KEY (`idPealkiri`),
  UNIQUE INDEX `teos_pealkiri` (`Pealkiri` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `haide`.`Autor_has_Teos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `haide`.`Autor_has_Teos` (
  `Autor_idAUtor` INT NOT NULL,
  `Teos_idPealkiri` INT NOT NULL,
  PRIMARY KEY (`Autor_idAUtor`, `Teos_idPealkiri`),
  INDEX `fk_Autor_has_Teos_Teos1_idx` (`Teos_idPealkiri` ASC),
  INDEX `fk_Autor_has_Teos_Autor_idx` (`Autor_idAUtor` ASC),
  CONSTRAINT `fk_Autor_has_Teos_Autor`
    FOREIGN KEY (`Autor_idAUtor`)
    REFERENCES `haide`.`Autor` (`idAUtor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Autor_has_Teos_Teos1`
    FOREIGN KEY (`Teos_idPealkiri`)
    REFERENCES `haide`.`Teos` (`idPealkiri`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `haide`.`Autor`
-- -----------------------------------------------------
START TRANSACTION;
USE `haide`;
INSERT INTO `haide`.`Autor` (`idAUtor`, `Eesnimi`, `Perekonnanimi`) VALUES (1, 'Haide', 'Kuivas');
INSERT INTO `haide`.`Autor` (`idAUtor`, `Eesnimi`, `Perekonnanimi`) VALUES (2, 'Tambet', 'Song');
INSERT INTO `haide`.`Autor` (`idAUtor`, `Eesnimi`, `Perekonnanimi`) VALUES (3, 'Mihkel ', 'Siim');
INSERT INTO `haide`.`Autor` (`idAUtor`, `Eesnimi`, `Perekonnanimi`) VALUES (4, 'Tarmo ', 'Dulinets');

COMMIT;


-- -----------------------------------------------------
-- Data for table `haide`.`Teos`
-- -----------------------------------------------------
START TRANSACTION;
USE `haide`;
INSERT INTO `haide`.`Teos` (`idPealkiri`, `Pealkiri`, `lk_arv`, `ilmumisaeg`) VALUES (1, 'Kvaliteet haridusorganisatsioonis', 49, 2012);
INSERT INTO `haide`.`Teos` (`idPealkiri`, `Pealkiri`, `lk_arv`, `ilmumisaeg`) VALUES (2, 'Metsamüügi käsiraamat', 30, 2010);
INSERT INTO `haide`.`Teos` (`idPealkiri`, `Pealkiri`, `lk_arv`, `ilmumisaeg`) VALUES (3, 'Tehnikaalased väljakutsed juhtidele', 70, 1998);
INSERT INTO `haide`.`Teos` (`idPealkiri`, `Pealkiri`, `lk_arv`, `ilmumisaeg`) VALUES (4, 'Kuldmedaliga lõpetajate uuring', 20, 2013);

COMMIT;


-- -----------------------------------------------------
-- Data for table `haide`.`Autor_has_Teos`
-- -----------------------------------------------------
START TRANSACTION;
USE `haide`;
INSERT INTO `haide`.`Autor_has_Teos` (`Autor_idAUtor`, `Teos_idPealkiri`) VALUES (1, 1);
INSERT INTO `haide`.`Autor_has_Teos` (`Autor_idAUtor`, `Teos_idPealkiri`) VALUES (2, 2);
INSERT INTO `haide`.`Autor_has_Teos` (`Autor_idAUtor`, `Teos_idPealkiri`) VALUES (3, 3);
INSERT INTO `haide`.`Autor_has_Teos` (`Autor_idAUtor`, `Teos_idPealkiri`) VALUES (4, 4);

COMMIT;

