-- MySQL Script generated by MySQL Workbench
-- 04/11/15 09:43:29
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema retseptiraamat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema retseptiraamat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `retseptiraamat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `retseptiraamat` ;

-- -----------------------------------------------------
-- Table `retseptiraamat`.`koostisosad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retseptiraamat`.`koostisosad` ;

CREATE TABLE IF NOT EXISTS `retseptiraamat`.`koostisosad` (
  `idkoostisosad` INT NOT NULL,
  `pealkiri` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idkoostisosad`),
  UNIQUE INDEX `pealkiri_UNIQUE` (`pealkiri` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retseptiraamat`.`retseptid`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retseptiraamat`.`retseptid` ;

CREATE TABLE IF NOT EXISTS `retseptiraamat`.`retseptid` (
  `idretsept` INT NOT NULL,
  `retsept` VARCHAR(45) NULL,
  PRIMARY KEY (`idretsept`),
  UNIQUE INDEX `retsept_UNIQUE` (`retsept` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `retseptiraamat`.`toidud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `retseptiraamat`.`toidud` ;

CREATE TABLE IF NOT EXISTS `retseptiraamat`.`toidud` (
  `retseptid_idretsept` INT NULL,
  `koostisosad_idkoostisosad` INT NULL,
  INDEX `fk_retseptid_has_koostisosad_koostisosad1_idx` (`koostisosad_idkoostisosad` ASC),
  INDEX `fk_retseptid_has_koostisosad_retseptid_idx` (`retseptid_idretsept` ASC),
  CONSTRAINT `fk_retseptid_has_koostisosad_retseptid`
    FOREIGN KEY (`retseptid_idretsept`)
    REFERENCES `retseptiraamat`.`retseptid` (`idretsept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_retseptid_has_koostisosad_koostisosad`
    FOREIGN KEY (`koostisosad_idkoostisosad`)
    REFERENCES `retseptiraamat`.`koostisosad` (`idkoostisosad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `retseptiraamat`.`koostisosad`
-- -----------------------------------------------------
START TRANSACTION;
USE `retseptiraamat`;
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (1, 'munad');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (2, 'piim');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (3, 'sool');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (4, 'vorst');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (5, 'suhkur');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (6, 'vesi');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (7, 'jahu');
INSERT INTO `retseptiraamat`.`koostisosad` (`idkoostisosad`, `pealkiri`) VALUES (8, 'kakaopulber');

COMMIT;


-- -----------------------------------------------------
-- Data for table `retseptiraamat`.`retseptid`
-- -----------------------------------------------------
START TRANSACTION;
USE `retseptiraamat`;
INSERT INTO `retseptiraamat`.`retseptid` (`idretsept`, `retsept`) VALUES (1, 'omlett');
INSERT INTO `retseptiraamat`.`retseptid` (`idretsept`, `retsept`) VALUES (2, 'pannkook');
INSERT INTO `retseptiraamat`.`retseptid` (`idretsept`, `retsept`) VALUES (3, 'kakao');

COMMIT;


-- -----------------------------------------------------
-- Data for table `retseptiraamat`.`toidud`
-- -----------------------------------------------------
START TRANSACTION;
USE `retseptiraamat`;
INSERT INTO `retseptiraamat`.`toidud` (`retseptid_idretsept`, `koostisosad_idkoostisosad`) VALUES (1, 1);
INSERT INTO `retseptiraamat`.`toidud` (`retseptid_idretsept`, `koostisosad_idkoostisosad`) VALUES (1, 2);
INSERT INTO `retseptiraamat`.`toidud` (`retseptid_idretsept`, `koostisosad_idkoostisosad`) VALUES (1, 3);
INSERT INTO `retseptiraamat`.`toidud` (`retseptid_idretsept`, `koostisosad_idkoostisosad`) VALUES (1, 4);

COMMIT;
use retseptiraamat;
desc koostisosad;
desc retseptid;
select * from koostisosad;
select * from retseptid;
select retseptid.retsept, koostisosad.pealkiri from toidud join retseptid on retseptid_idretsept=idretsept join koostisosad on koostisosad_idkoostisosad=idkoostisosad;
select retseptid.retsept, koostisosad.pealkiri, 
count(koostisosad.pealkiri)
from toidud 
join retseptid on retseptid_idretsept=idretsept 
join koostisosad on koostisosad_idkoostisosad=idkoostisosad 
having pealkiri in ("i")
order by pealkiri desc, retsept asc;
delete from koostisosad where idkoostisosad < 8;
delete from retseptid where idretsept <8;
delete from toidud where retseptid_idretsept < 3;
