-- MySQL Script generated by MySQL Workbench
-- 05/04/15 18:50:12
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ois
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ois` ;
CREATE SCHEMA IF NOT EXISTS `ois` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `ois` ;

-- -----------------------------------------------------
-- Table `ois`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`roles` (
  `id_roles` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `role` SET('student', 'admin', 'teacher') NOT NULL,
  PRIMARY KEY (`id_roles`),
  UNIQUE INDEX `role_UNIQUE` (`role` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`groups` (
  `id_groups` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `groupname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_groups`),
  UNIQUE INDEX `groupname_UNIQUE` (`groupname` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`users` (
  `id_users` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role_id_roles` INT UNSIGNED NOT NULL,
  `groups_id_groups` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_users`),
  INDEX `fk_users_role1_idx` (`role_id_roles` ASC),
  INDEX `fk_users_groups1_idx` (`groups_id_groups` ASC),
  CONSTRAINT `fk_users_role1`
    FOREIGN KEY (`role_id_roles`)
    REFERENCES `ois`.`roles` (`id_roles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_groups1`
    FOREIGN KEY (`groups_id_groups`)
    REFERENCES `ois`.`groups` (`id_groups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`phones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`phones` (
  `id_phones` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `phone` VARCHAR(45) NOT NULL,
  `users_id_users` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_phones`),
  INDEX `fk_phones_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_phones_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`lessontypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`lessontypes` (
  `id_lessontypes` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_lessontypes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`modules` (
  `id_modules` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `length` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_modules`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`rooms` (
  `id_rooms` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room` VARCHAR(45) NOT NULL,
  `seats` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rooms`),
  UNIQUE INDEX `room_UNIQUE` (`room` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`lessons` (
  `id_lessons` INT UNSIGNED NULL AUTO_INCREMENT,
  `modules_id_modules` INT UNSIGNED NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `date` DATETIME NOT NULL,
  `lessontypes_id_lessontypes` INT UNSIGNED NOT NULL,
  `rooms_id_rooms` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_lessons`),
  INDEX `fk_lessons_modules1_idx` (`modules_id_modules` ASC),
  INDEX `fk_lessons_lessontypes1_idx` (`lessontypes_id_lessontypes` ASC),
  INDEX `fk_lessons_rooms1_idx` (`rooms_id_rooms` ASC),
  CONSTRAINT `fk_lesson_module1`
    FOREIGN KEY (`modules_id_modules`)
    REFERENCES `ois`.`modules` (`id_modules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lesson_lessonType1`
    FOREIGN KEY (`lessontypes_id_lessontypes`)
    REFERENCES `ois`.`lessontypes` (`id_lessontypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_lessons_rooms1`
    FOREIGN KEY (`rooms_id_rooms`)
    REFERENCES `ois`.`rooms` (`id_rooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`reasons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`reasons` (
  `id_reasons` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reason` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`id_reasons`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`absences`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`absences` (
  `id_absences` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `users_id_users` INT UNSIGNED NOT NULL,
  `reasons_id_reasons` INT UNSIGNED NOT NULL,
  `has_reason` TINYINT(1) NOT NULL,
  `lessons_id_lessons` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_absences`),
  INDEX `fk_users_has_absenses_users1_idx` (`users_id_users` ASC),
  INDEX `fk_absences_reasons1_idx` (`reasons_id_reasons` ASC),
  INDEX `fk_abcenses_lessons1_idx` (`lessons_id_lessons` ASC),
  CONSTRAINT `fk_users_has_absenses_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_absences_reasons1`
    FOREIGN KEY (`reasons_id_reasons`)
    REFERENCES `ois`.`reasons` (`id_reasons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_abcenses_lessons1`
    FOREIGN KEY (`lessons_id_lessons`)
    REFERENCES `ois`.`lessons` (`id_lessons`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`rooms_has_modules`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`rooms_has_modules` (
  `id_rooms_has_modules` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modules_id_modules` INT UNSIGNED NOT NULL,
  `rooms_id_rooms` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_rooms_has_modules`),
  INDEX `fk_rooms_has_modules_modules1_idx` (`modules_id_modules` ASC),
  INDEX `fk_rooms_has_modules_rooms1_idx` (`rooms_id_rooms` ASC),
  CONSTRAINT `fk_rooms_has_module_rooms1`
    FOREIGN KEY (`rooms_id_rooms`)
    REFERENCES `ois`.`rooms` (`id_rooms`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rooms_has_module_module1`
    FOREIGN KEY (`modules_id_modules`)
    REFERENCES `ois`.`modules` (`id_modules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`modules_has_groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`modules_has_groups` (
  `id_modules_has_groups` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modules_id_modules` INT UNSIGNED NOT NULL,
  `groups_id_groups` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_modules_has_groups`),
  INDEX `fk_modules_has_groups_groups1_idx` (`groups_id_groups` ASC),
  INDEX `fk_modules_has_groups_modules1_idx` (`modules_id_modules` ASC),
  CONSTRAINT `fk_module_has_groups_module1`
    FOREIGN KEY (`modules_id_modules`)
    REFERENCES `ois`.`modules` (`id_modules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_has_groups_groups1`
    FOREIGN KEY (`groups_id_groups`)
    REFERENCES `ois`.`groups` (`id_groups`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`homeworks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`homeworks` (
  `id_homeworks` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date_due` DATE NOT NULL,
  `description` MEDIUMTEXT NOT NULL,
  `modules_id_modules` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_homeworks`),
  INDEX `fk_homeworks_modules1_idx` (`modules_id_modules` ASC),
  CONSTRAINT `fk_homeworks_modules1`
    FOREIGN KEY (`modules_id_modules`)
    REFERENCES `ois`.`modules` (`id_modules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`modules_has_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`modules_has_users` (
  `id_modules_users` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modules_id_modules` INT UNSIGNED NOT NULL,
  `users_id_users` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_modules_users`),
  INDEX `fk_modules_has_users_users1_idx` (`users_id_users` ASC),
  INDEX `fk_modules_has_users_modules1_idx` (`modules_id_modules` ASC),
  CONSTRAINT `fk_module_has_users_module1`
    FOREIGN KEY (`modules_id_modules`)
    REFERENCES `ois`.`modules` (`id_modules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_module_has_users_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`modules_has_lessontypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`modules_has_lessontypes` (
  `modules_id_modules` INT UNSIGNED NOT NULL,
  `lessontypes_id_lessontypes` INT UNSIGNED NOT NULL,
  `percent` FLOAT(2,1) NOT NULL COMMENT 'hinnete osakaalu laine lõpphindest',
  INDEX `fk_modules_has_lessontypes_lessontypes1_idx` (`lessontypes_id_lessontypes` ASC),
  INDEX `fk_modules_has_lessontypes_modules1_idx` (`modules_id_modules` ASC),
  CONSTRAINT `fk_modules_has_lessonTypes_modules1`
    FOREIGN KEY (`modules_id_modules`)
    REFERENCES `ois`.`modules` (`id_modules`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modules_has_lessonTypes_lessonTypes1`
    FOREIGN KEY (`lessontypes_id_lessontypes`)
    REFERENCES `ois`.`lessontypes` (`id_lessontypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`grade` (
  `grades_id_grades` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `modules_has_users_id_modules_users` INT UNSIGNED NOT NULL,
  `modules_has_lessontypes_modules_id_modules` INT UNSIGNED NOT NULL,
  `modules_has_lessontypes_lessontypes_id_lessontypes` INT UNSIGNED NOT NULL,
  `grade` ENUM('1','2','3', '4', '5', 'ma', 'a') NOT NULL,
  PRIMARY KEY (`grades_id_grades`),
  INDEX `fk_modules_has_users_has_grades_modules_has_users1_idx` (`modules_has_users_id_modules_users` ASC),
  INDEX `fk_modules_has_users_has_grades_modules_has_lessontypes1_idx` (`modules_has_lessontypes_modules_id_modules` ASC, `modules_has_lessontypes_lessontypes_id_lessontypes` ASC),
  CONSTRAINT `fk_modules_has_users_has_grades_modules_has_users1`
    FOREIGN KEY (`modules_has_users_id_modules_users`)
    REFERENCES `ois`.`modules_has_users` (`id_modules_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_modules_has_users_has_grades_modules_has_lessonTypes1`
    FOREIGN KEY (`modules_has_lessontypes_modules_id_modules` , `modules_has_lessontypes_lessontypes_id_lessontypes`)
    REFERENCES `ois`.`modules_has_lessontypes` (`modules_id_modules` , `lessontypes_id_lessontypes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`bad_days`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`bad_days` (
  `id_bad_days` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id_bad_days`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`user_period_datetime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`user_period_datetime` (
  `id_user_period_datetime` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `begins` DATETIME NOT NULL,
  `ends` DATETIME NOT NULL,
  `users_id_users` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user_period_datetime`),
  INDEX `fk_users_period_datetime_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_user_period_datetime_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`user_period_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`user_period_day` (
  `id_user_period_day` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `day` ENUM('e', 't', 'k', 'n', 'r', 'l') NOT NULL,
  `begins` DATETIME NOT NULL,
  `ends` DATETIME NOT NULL,
  `weeks_in_row` TINYINT UNSIGNED NOT NULL,
  `users_id_users` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user_period_day`),
  INDEX `fk_users_period_day_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_user_period_day_users1`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`group_period_day`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`group_period_day` (
  `id_group_period_day` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `day` ENUM('e', 't', 'k', 'n', 'r', 'l') NOT NULL,
  `begins` DATETIME NOT NULL,
  `ends` DATETIME NOT NULL,
  `weeks_in_row` TINYINT UNSIGNED NOT NULL,
  `users_id_users` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_group_period_day`),
  INDEX `fk_users_period_day_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_user_period_day_users10`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ois`.`group_period_datetime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ois`.`group_period_datetime` (
  `id_group_period_datetime` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `begins` DATETIME NOT NULL,
  `ends` DATETIME NOT NULL,
  `users_id_users` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_group_period_datetime`),
  INDEX `fk_users_period_datetime_users1_idx` (`users_id_users` ASC),
  CONSTRAINT `fk_user_period_datetime_users10`
    FOREIGN KEY (`users_id_users`)
    REFERENCES `ois`.`users` (`id_users`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
