-- MySQL Script generated by MySQL Workbench
-- 01/30/15 20:48:03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema xml
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `xml` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `xml` ;

-- -----------------------------------------------------
-- Table `xml`.`SportsType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xml`.`SportsType` (
  `idSportsType` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`idSportsType`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `xml`.`Event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `xml`.`Event` (
  `idEvent` INT NOT NULL AUTO_INCREMENT,
  `place` VARCHAR(45) NULL,
  `info` TEXT NULL,
  `start` DATETIME NULL,
  `end` DATETIME NULL,
  `SportsType_idSportsType` INT NOT NULL,
  PRIMARY KEY (`idEvent`, `SportsType_idSportsType`),
  INDEX `fk_event_SportsType_idx` (`SportsType_idSportsType` ASC),
  CONSTRAINT `fk_event_SportsType`
    FOREIGN KEY (`SportsType_idSportsType`)
    REFERENCES `xml`.`SportsType` (`idSportsType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
